# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTsM_20x1LkirqBaPUqxpwJssz8QKXXR
"""

import sqlite3
import time
import os
import random

# ANSI Escape Codes for Terminal Colors
class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def setup_database():
    if os.path.exists('audit_tool.db'):
        try:
            os.remove('audit_tool.db')
        except PermissionError:
            pass

    conn = sqlite3.connect('audit_tool.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS trades
                 (id INTEGER, ticker TEXT, execution_date TEXT, side TEXT, price REAL, quantity INTEGER)''')

    print(f"{Colors.OKBLUE}[SYSTEM]{Colors.ENDC} Generating 100,000 synthetic trade records...")

    tickers = ["AAPL", "SPY", "TSLA", "NVDA"]
    sides = ["BUY", "SELL"]
    data = []
    for i in range(100000):
        t = tickers[i % 4]
        date = f"2026-03-{(i % 30) + 1:02d}"
        side = sides[i % 2]
        price = round(random.uniform(100.0, 500.0), 2)
        qty = random.choice([100, 200, 500, 1000])
        data.append((i, t, date, side, price, qty))

    c.executemany('INSERT INTO trades VALUES (?, ?, ?, ?, ?, ?)', data)
    conn.commit()
    print(f"{Colors.OKGREEN}[SUCCESS]{Colors.ENDC} Database populated and ready.\n")
    return conn, c

def run_operation(c, title, query, params, iters=100):
    print(f"\n{Colors.HEADER}{Colors.BOLD}>>> {title} <<<{Colors.ENDC}")
    # Display the query and the safe parameters we are passing
    print(f"{Colors.BOLD}[SQL]{Colors.ENDC} {query} | {Colors.WARNING}Params: {params}{Colors.ENDC}")

    # 1. High-Level Execution Plan
    print(f"\n{Colors.BOLD}[PLAN]{Colors.ENDC} High-Level Execution Plan:")
    for row in c.execute("EXPLAIN QUERY PLAN " + query, params):
        print(" ->", row[3])

    # 2. VDBE Bytecode
    print(f"\n{Colors.BOLD}[VDBE]{Colors.ENDC} Bytecode (First 12 instructions):")
    bytecode_rows = c.execute("EXPLAIN " + query, params).fetchmany(12)
    for row in bytecode_rows:
        print(f" -> Opcode: {row[1]:<15} | P1: {row[2]:<5} | P2: {row[3]:<5} | P3: {row[4]}")

    # 3. Execution & Stress Test
    print(f"\n{Colors.BOLD}[APP]{Colors.ENDC} Fetching matching records (Stress Test: {iters} iterations)...")
    start_time = time.time()

    for _ in range(iters):
        results = c.execute(query, params).fetchall()
    end_time = time.time()

    if results:
        print(f"{Colors.OKGREEN}Found {len(results)} matches. Displaying top 3:{Colors.ENDC}")
        for r in results[:3]:
            print(f"  ID: {r[0]:<6} | Ticker: {r[1]:<5} | Date: {r[2]} | {r[3]:<4} | Qty: {r[5]:<5} | Px: ${r[4]:.2f}")
    else:
        print(f"  {Colors.FAIL}No records found.{Colors.ENDC}")

    print(f"{Colors.BOLD}Total execution time ({iters} queries): {end_time - start_time:.5f} seconds{Colors.ENDC}\n")
    print("-" * 60)

def main():
    clear_screen()
    print(f"{Colors.HEADER}{Colors.BOLD}================================================={Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}       QUANTITATIVE TRADE AUDIT SYSTEM           {Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}================================================={Colors.ENDC}\n")

    conn, c = setup_database()

    # Get inputs for the operations
    user_ticker = input(f"Enter ticker to audit (e.g., AAPL, SPY): ").strip().upper()
    single_date = input(f"Enter specific date for Point Lookup (e.g., 2026-03-15): ").strip()
    start_date = input(f"Enter START date for Range Scan (e.g., 2026-03-01): ").strip()
    end_date = input(f"Enter END date for Range Scan (e.g., 2026-03-07): ").strip()

    # Define the queries using ? placeholders
    q1_point = "SELECT * FROM trades WHERE ticker = ? AND execution_date = ?"
    q2_range = "SELECT * FROM trades WHERE ticker = ? AND execution_date BETWEEN ? AND ?"
    q3_sort = "SELECT * FROM trades WHERE ticker = ? ORDER BY execution_date DESC LIMIT 5"

    print(f"\n{Colors.FAIL}{Colors.BOLD}=== PHASE 1: UNINDEXED (FULL TABLE SCANS) ==={Colors.ENDC}")
    run_operation(c, "OP 1: POINT LOOKUP", q1_point, (user_ticker, single_date))
    run_operation(c, "OP 2: RANGE SCAN", q2_range, (user_ticker, start_date, end_date))
    run_operation(c, "OP 3: TOP-K SORT", q3_sort, (user_ticker,))

    input(f"{Colors.WARNING}Press Enter to build the composite B-Tree index on (ticker, execution_date)...{Colors.ENDC}")
    c.execute('CREATE INDEX idx_ticker_date ON trades(ticker, execution_date)')
    print(f"{Colors.OKGREEN}Index 'idx_ticker_date' built successfully.{Colors.ENDC}\n")

    print(f"\n{Colors.OKBLUE}{Colors.BOLD}=== PHASE 2: INDEXED (B-TREE TRAVERSAL) ==={Colors.ENDC}")
    run_operation(c, "OP 1: POINT LOOKUP", q1_point, (user_ticker, single_date))
    run_operation(c, "OP 2: RANGE SCAN", q2_range, (user_ticker, start_date, end_date))
    run_operation(c, "OP 3: TOP-K SORT", q3_sort, (user_ticker,))

    conn.close()

if __name__ == "__main__":
    main()